project:
  type: website
  output-dir: _site

website:
  title: "Mohammad Tanvir Hasan"
  description: "Personal site and blog"
  site-url: "https://tanvircr7.github.io/mtanvir"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: notes/index.qmd
        text: Notes
      - href: taxonomy/index.qmd
        text: Topics
    right:
      - icon: rss
        href: blog/index.xml
  page-footer:
    center: "© 2025 Mohammad Tanvir Hasan"
  repo-url: "https://github.com/tanvircr7/mtanvir"
  repo-actions: [source]


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true

    # theme:
    #   light: cosmo
    #   dark: darkly
    # css: styles.css
    # toc: true
    # smooth-scroll: true

execute:
  freeze: auto
